import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css"
import { cn } from "@/lib/utils"
import {SideNavbar} from "@/components/SideNavbar";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex", 
          fontSans.variable
        )}
      >
        <SideNavbar />
        {/* sidebar */}
        {/* main page */}
        <div className="p-8 w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
